apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auth-depl.yaml
- auth-mongo-depl.yaml
- orders-depl.yaml
- orders-mongo-depl.yaml
- expiration-depl.yaml
- expiration-redis-depl.yaml
- ingress-ser.yaml
- nats-depl.yaml
- payments-depl.yaml
- payments-mongo-depl.yaml
- tickets-depl.yaml
- tickets-mongo-depl.yaml
- client-depl.yaml


