name: Deploy-auth

on:
  push:
    branches: [ "main" ]
    paths:
      - 'auth/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd auth && docker build -t ndife/auth .
      
    - name: Login to Docker Hub
      run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      
    # import env variables 
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        
    # push to docker hub  
    - run: docker push ndife/auth
