# This is a workflow for running the payments-tests

name: payments-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch and only when changes occur in this file path
  pull_request:
    branches: [ "main" ]
    paths:
      - 'payments/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JWT_KEY: ${{ secrets.JWT_KEY }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run tests on payments service
        run: cd payments && npm install && npm run test:ci

